### ISSUE TITLE
Title, spaces around URLs

### ISSUE THREAD

**Issue by prc1212** [ttscoff/gather-cli#1]
First of all, this is fabulous! I've been looking for something like this for ages. It'll let me replace the GUI scripting I've been using to export decluttered PDFs from Safari to DEVONthink.

Just a couple of points re the output.

First, Gather leaves out the page title. For things like news articles, it's probably preferable to keep the title at the top of the page.

Second, there are no spaces between URL syntax and surrounding text. E.g.: "some text[title][1]text continues."

**Comment by denwald** [comment]
Hi, also wanted to say how happy I am to have found this tool. It could be very useful to populate my extensive library of notes I keep on programming and other topics. 

I thought the missing title was just a problem with extracting it from the pages I tested gather with. If it's intentional, maybe a flag to include the title would be useful?

Also, the [CHANGELOG.md](https://github.com/ttscoff/gather-cli/blob/main/CHANGELOG.md) in the repository is a symlink that points to nowhere. Leaving this here because I did not want to open a separate issue for this.

**Comment by ttscoff** [comment]
Deploying the fix for both issues right now, check for version 2.0.23 in a few minutes.

**Comment by ttscoff** [comment]
Oh and the changelog thing was because it was a symlink from my blog. I've reversed it so the original is in the repo and the symlink is in the blog for rendering the project there.

**Comment by little-flag** [comment]
The `--include-title` flag appears not to work when using piped input. The following returns markdown without the title:

```
tell application "Safari"
	if exists front window then tell front window to tell current tab
		set theHTML to source
	end tell
end tell
return do shell script "echo " & quoted form of theHTML & " | /usr/local/bin/gather --stdin --html --include-title"
```

N.B. it works when called from AppleScript via the URL.

2.0.29

**Comment by ttscoff** [comment]
Should be in better shape now, just pushed 2.0.30.

**Comment by little-flag** [comment]
Getting closer! However, there is still a problem. Using the `--no-include-source` flag seems to prevent the title being included when being passed a URL directly. I.e. this doesn’t work properly:

`gather --no-include-source --include-title [URL]`

Thanks and take it easy.

**Comment by little-flag** [comment]
Deleted my last comment as it was incorrect (just in case you got a notification and are now confused). 

The latest version resolves the issue I previously mentioned. However, I am finding that e.g. this is not returning the title:

`gather --include-title https://www.theguardian.com/uk-news/2022/sep/02/liz-truss-law-and-order-policies-meaningless-says-police-chief`

Thanks and take it easy!

**Comment by ttscoff** [comment]
Ah, it was failing to output the title if a rel=canonical url wasn't found. Fixed in the 2.0.41, which should be available shortly.

**Comment by ttscoff** [comment]
Will have to look into this when I get a chance. Development is going to 
slow a bit over the next couple of weeks but I should find time to look 
at it.

**Comment by ttscoff** [comment]
2.0.42 should fix the missing title.
