### ISSUE TITLE
Feature Request: frontmatter support

### ISSUE THREAD

**Issue by jgclark** [ttscoff/gather-cli#10]
This is looking to be a great tool for macOS.
I don't know nvUltra yet, so I don't know if it supports YAML-style frontmatter blocks, but I'm trying to standardise on new notes having them. If gather could also have a `--frontmatter` option that simply adds `---` lines before and after the metadata, then that would be great.
Thank you for considering this.

**Comment by chrisgrieser** [comment]
already exists, use `--metadata-yaml`

**Comment by jgclark** [comment]
Many thanks, that works just as hoped.
