### ISSUE TITLE
Bug: fails to correctly scrap the content from the new TheVerge Layout

### ISSUE THREAD

**Issue by chrisgrieser** [ttscoff/gather-cli#12]
To reproduce, run:

```zsh
gather "https://www.theverge.com/2022/4/23/23038870/apple-app-store-widely-remove-outdated-apps-developers"
```

The very same article was parsed correctly just yesterday before the layout. Trying again today, to retrieve the article content and instead grabbed some teaser for a different article instead.

**Comment by ttscoff** [comment]
I apparently fixed this with some other changes, as running the above command now gives me the full content of the article. (v2.0.44)
