### ISSUE TITLE
Can't parse notion pages - 2.1.0

### ISSUE THREAD

**Issue by luckman212** [ttscoff/gather-cli#15]
I know this is a low- or nil-priority thing, but recently I tried to use gather to parse this page:

https://chaudhry.notion.site/I-wish-GPT4-had-never-happened-9f0cbf2848a44ec9911c07fb34ff5de3

It seems to only extract the Title, not the meat that's in the lower frame.

Thanks for making this.

**Comment by ttscoff** [comment]
Notion pages are populated by JavaScript, none of the actual content is in the downloaded page. In order to clip a Notion page, you'll have to use a Shortcut that passes selected text to gather, or copy the content of the page with ⌘C and then use `gather --paste --html`.

**Comment by luckman212** [comment]
Thanks @ttscoff 

I couldn't really figure this out. Maybe someone else who's better with Shortcuts can make it work...

I made a Shortcut, e.g.

![image](https://user-images.githubusercontent.com/1992842/234950814-37d1bfe5-08cc-45b9-9e43-afb563ff8ede.png)


```
shortcuts run 'URL to Text' <<<'https://chaudhry.notion.site/I-wish-GPT4-had-never-happened-9f0cbf2848a44ec9911c07fb34ff5de3' --output-path foo
```

But I just end up with some crazy blob of data 

<img width="935" alt="image" src="https://user-images.githubusercontent.com/1992842/234951096-d2a1e5b5-dfbe-4d7f-ad8f-ce5b4f35beb8.png">

**Comment by ttscoff** [comment]
Your shortcut would have to actually run gather… if you're getting the 
contents of a web page you may or may not get actual usable data. You 
shortcut would be better served to get the current selection of web text 
and run `gather --stdin --html` on it.
