### ISSUE TITLE
Full Xcode IDE needed for building?

### ISSUE THREAD

**Issue by denwald** [ttscoff/gather-cli#2]
This is more of a question rather than an issue. Sorry if this is obvious for experienced Mac devs.

Is it possible to compile the gather-cli executable with only the _Command Line Tools_ installed? The _Command Line Tools_ come with the _swift_ and the _swiftc_ command. In fact, I have successfully compiled very simple sample programs in Swift already. When I try to compile gather-cli though, using the instructions in the README, I get the following error:

`xcrun: error: unable to find utility "xctest", not a developer tool or in PATH`

Unfortunately I don't have enough space currently to install the full Xcode IDE.

**Comment by mfessler** [comment]
I have the Xcode IDE installed (version 13.4.1) and am having the same issue. 

I think there's more going on, though. Here is a full error log:

```make
install
prefix=/opt/homebrew/Cellar/gather-cli/2.0.25

swift build -c release --disable-sandbox
warning: Failed creating default security location, Error Domain=NSCocoaErrorDomain Code=513 "You don’t have permission to save the file “security” in the folder “org.swift.swiftpm”." UserInfo={NSFilePath=/Users/mef/Library/org.swift.swiftpm/security, NSUnderlyingError=0x6000012063d0 {Error Domain=NSPOSIXErrorDomain Code=1 "Operation not permitted"}}
warning: Failed creating default configuration location, Error Domain=NSCocoaErrorDomain Code=513 "You don’t have permission to save the file “configuration” in the folder “org.swift.swiftpm”." UserInfo={NSFilePath=/Users/mef/Library/org.swift.swiftpm/configuration, NSUnderlyingError=0x6000012079f0 {Error Domain=NSPOSIXErrorDomain Code=1 "Operation not permitted"}}
warning: Failed creating default cache location, Error Domain=NSCocoaErrorDomain Code=513 "You don’t have permission to save the file “org.swift.swiftpm” in the folder “Caches”." UserInfo={NSFilePath=/Users/mef/Library/Caches/org.swift.swiftpm, NSUnderlyingError=0x600001208990 {Error Domain=NSPOSIXErrorDomain Code=1 "Operation not permitted"}}
error: terminated(72): /usr/bin/xcrun --sdk macosx --find xctest output:
    xcrun: error: unable to find utility "xctest", not a developer tool or in PATH

make: *** [build] Error 1```

**Comment by mfessler** [comment]
OK, I was able to get it installed, but it did require the IDE.
```
$ xcode-select -p
/Library/Developer/CommandLineTools

sudo xcode-select -r
Password:
$ xcode-select -p
/Applications/Xcode.app/Contents/Developer
```
After this, installation worked.

**Comment by krzysztofjeziorny** [comment]
I saw it, too: having just the Command Line Tools is not enough. I'd love to avoid installing XCode if possible.

>`gather-cli: A full installation of Xcode.app 10.0 is required to compile this software. Installing just the Command Line Tools is not sufficient.`
>`Xcode can be installed from the App Store.
Error: gather-cli: An unsatisfied requirement failed this build.`

**Comment by ttscoff** [comment]
I might eventually figure out how to offer a Homebrew bottle, but in order to do so I need in compiled for every possible OS it will work on and I haven't figured out how to do that yet. So it's build-from-source only for now.

There's always the package installer if you can't handle installing Xcode for now...

**Comment by ttscoff** [comment]
You could also always try cloning the repository and running

    swift build -c release --disable-sandbox
    cp ./.build/apple/Products/Release/gather /usr/local/bin/

Not sure if it will work without `xcrun swift build...` but worth a shot. Then you can update just by pulling the latest git repo (which is updated with every release) and compiling your own.

**Comment by ttscoff** [comment]
There's a make file to make it as easy as `make install`, which will build and install in one step.

**Comment by pahles** [comment]
I have the full Xcode IDE installed but receive the following warning:

> swift build -c release --disable-sandbox
warning: Failed creating default cache locations, Error Domain=NSCocoaErrorDomain Code=513 "You don’t have permission to save the file “org.swift.swiftpm” in the folder “Caches”." UserInfo={NSFilePath=/Users/pahles/Library/Caches/org.swift.swiftpm, NSUnderlyingError=0x7fd2674076c0 {Error Domain=NSPOSIXErrorDomain Code=1 "Operation not permitted"}}
warning: Failed creating default config locations, Error Domain=NSCocoaErrorDomain Code=513 "You don’t have permission to save the file “org.swift.swiftpm” in the folder “Library”." UserInfo={NSFilePath=/Users/pahles/Library/org.swift.swiftpm, NSUnderlyingError=0x7fd277421580 {Error Domain=NSPOSIXErrorDomain Code=1 "Operation not permitted"}}
warning: Failed creating default cache locations, Error Domain=NSCocoaErrorDomain Code=513 "You don’t have permission to save the file “org.swift.swiftpm” in the folder “Caches”." UserInfo={NSFilePath=/Users/pahles/Library/Caches/org.swift.swiftpm, NSUnderlyingError=0x7fd267607370 {Error Domain=NSPOSIXErrorDomain Code=1 "Operation not permitted"}}
/private/tmp/gather-cli-20220904-83199-enjbie: error: package at '/private/tmp/gather-cli-20220904-83199-enjbie' is using Swift tools version 5.6.0 but the installed version is 5.5.0
make: *** [build] Error 1

**Comment by mfessler** [comment]
This is the same issue I encountered above. Turns out I needed to use xcode-select to point to the full IDE rather than the CLI tools. https://github.com/ttscoff/gather-cli/issues/2#issuecomment-1232307929

**Comment by pahles** [comment]
> This is the same issue I encountered above. Turns out I needed to use xcode-select to point to the full IDE rather than the CLI tools. [#2 (comment)](https://github.com/ttscoff/gather-cli/issues/2#issuecomment-1232307929)

Which I did:

```
$ sudo xcode-select -p
/Applications/Xcode.app/Contents/Developer
```

Still get the error as mentioned in https://github.com/ttscoff/gather-cli/issues/2#issuecomment-1236278238, which is not the same error as you got.

**Comment by pahles** [comment]
Turns out, because I'm still on Big Sur, installing with homebrew will not work. According to `Package.swift` Swift 5.6 is needed. The most recent Xcode on Big Sur is 13.2.1, which ships with Swift 5.5.

I guess it's time to bite the bullet, hoping the rest of my development stack won't come to a stop.

**Comment by languidphoton** [comment]
Same issue as /u/pahles. I edited the `Package.swift` in `Library/Caches/Homebrew/gather-cli--git` to make the minimum swift usable as 5.5.0, ie `swift-tools-version: 5.5.0`.

But the code was too smart for me :)

```
/Users/languid/Library/Caches/Homebrew/gather-cli--git/.build/checkouts/swift-argument-parser/Sources/ArgumentParser/Parsable Types/AsyncParsableCommand.swift:23:23: error: concurrency is only available in macOS 12.0.0 or newer
  mutating func run() async throws
```

Ah well, looks like I do need to pull the trigger on that M1 Air I was looking at (seems a better value than an M2, and I love the form factor) - my 2014 MBA has done some sterling service though.

**Comment by jgclark** [comment]
> There's a make file to make it as easy as `make install`, which will build and install in one step.

Not having enough space to add Xcode, I tried this, and sadly gives similar errors to others reporting it.
```
error: terminated(72): /usr/bin/xcrun --sdk macosx --find xctest output:
    xcrun: error: unable to find utility "xctest", not a developer tool or in PATH
```

Perhaps for now you could put a note on the main Gather page saying it needs full Xcode and that is a download of at least 12GB (according to macupdates.com). I don't know how much space it expands to after that.

**Comment by ttscoff** [comment]
There’s an 8 MB PKG download with recompiled binaries. See the release page.

Thanks,
Brett

**Comment by chrisgrieser** [comment]
yeah, I was also a bit irritated having to install 12GB of Xcode just to built this cli 🙈

But can confirm, simply using the package installer works just fine and makes this whole process easier...

**Comment by pahles** [comment]
> Turns out, because I'm still on Big Sur, installing with homebrew will not work. According to `Package.swift` Swift 5.6 is needed. The most recent Xcode on Big Sur is 13.2.1, which ships with Swift 5.5.
> 
> I guess it's time to bite the bullet, hoping the rest of my development stack won't come to a stop.

Updated to Monterey this week. After updating Xcode I was able to install gather the homebrew way.
