### ISSUE TITLE
Shortcut "Gather to nvUtra" runs but nothing is produced in nvUltra notebook

### ISSUE THREAD

**Issue by rlguibord** [ttscoff/gather-cli#20]
I am excited about your Gather project and have read almost everything you have written about it on your site. I installed and updated Gather CLI via Homebrew, and added the provided "Gather to nvUltra" shortcut to my system. I activate it through Launchbar, and it seems to run, including a success Notification, but nothing shows up in my nvUltra notebook. I tried it with and without specifying a full path, but either way, nothing is showing up in nvUltra. I attempted using it as a web clipper after selecting text in Safari(not sure if that is an intended use, but hoping), and after copying the url to the clipboard. Still nothing. 
Please advise.
Robert Guibord

**Comment by ttscoff** [comment]
I can verify that the shortcut works for me. Can you try running the command from the shortcut directly in Terminal and seeing if it works? Also, are you running with a URL in the clipboard?

**Comment by rlguibord** [comment]
It works in the Terminal, but in Shortcuts I now get a “command not found” dialogue. See attached screenshot.
￼

**Comment by rlguibord** [comment]
I figured this out and got it working. It was a matter of completing the installation correctly. The last issue I mentioned above, the "command not found" message, was caused by my not taking fully into account my shift from bash to zsh. I used your method [here](https://brettterpstra.com/2022/09/28/homebrew-and-slash-usr-slash-local-slash-bin-on-m1-macs/) and that solved my problem. 
Thank you.

**Comment by ttscoff** [comment]
Awesome, glad to hear it.
