### ISSUE TITLE
Gather file location

### ISSUE THREAD

**Issue by ELBeavers** [ttscoff/gather-cli#6]
I installed Gather using `brew`, which installed the binary in `/opt/homebrew/bin/gather`. I noticed your package installed places the binary in `/usr/local/bin`. Your latest Popclip WebMD extension doesn't recognize that I have it installed.

Also, Gather does not appear to be gathering anything for me. For example, the following yields an empty file.

`gather https://brettterpsra.com >> ~/Desktop/ttscoff.md`

I'm willing to share any logs or info from my Mac as well as my time to assist.

**Comment by ttscoff** [comment]
Yeah, I always forget that I symlinked /opt/homebrew/bin to 
/usr/local/bin and all of my binaries are available at both. I kinda 
recommend everybody do that, but I'll update the PopClip extension to 
just expect `gather` to be in the PATH and not provide a filepath.

Run `gather --help` for me and make sure it's actually running. I test 
it on https://brettterpstra.com all the time and have never had it 
return empty.

**Comment by ELBeavers** [comment]
Yep, it's running and `/opt/homebrew/bin` is in my `$PATH`.

```
❯ which gather
/opt/homebrew/bin/gather
❯ gather -v
gather-cli v2.0.33
```

Tried the same command as above just now and still got a blank file.

**Comment by ttscoff** [comment]
what happens if you use an option like --copy, does it at least try to tell you it put something in the clipboard? Like is it giving you any feedback at all?

**Comment by ELBeavers** [comment]
Close this issue. We *both* missed a typo in the URL. 🤯

It works just fine when I type the address correctly. Thanks for the attention, but sorry for the distraction!

**Comment by ttscoff** [comment]
Phew :)
