### ISSUE TITLE
Gather to Obsidian

### ISSUE THREAD

**Issue by DeLub** [ttscoff/gather-cli#7]
Thanks for Gather.

As you asked for additional note platforms to add: I would really appreciate an option for Obsidian.

**Comment by ttscoff** [comment]
So I looked into Obsidian and it seems easy enough. However, instead of adding a ton of different options for every possible notes app, I instead added a `--url-template` option that lets you build your own URL. E.g.:

    gather --url-template="x-nvultra://make/?title=%title&text=%text&notebook=%notebook

See the README for more info.

**Comment by DeLub** [comment]
Thanks!

This works:
```
gather -f test.md --metadata --url-template "obsidian://new?vault=HomeBase&name=%filename&content=%text" --url-open https://brettterpstra.com
```

But when I add `--no-include-source` (because this is already part of the metadata) the heading with the pagetitle is not written to the note.

**Comment by ttscoff** [comment]
I'll have to look into this. The metadata header should still be 
written, even without the source. Will update soon.

**Comment by ttscoff** [comment]
2.0.43 should fix the issue.

**Comment by DeLub** [comment]
Finally got around to it. It works now! Thank you so much!

**Comment by ttscoff** [comment]
btw, you can use `--metadata-yaml` to include YAML markers around the metadata if you prefer now.

**Comment by DeLub** [comment]
Even better. Thanks again!
