### ISSUE TITLE
Gather shortcut file save

### ISSUE THREAD

**Issue by OllieA** [ttscoff/gather-cli#9]
Installed gather with homebrew. Works well from command line. Then installed Gather shortcut and bookmarklet. Had to add full path to gather (/opt/homebrew/bin) in the shortcut even though $PATH shows this location in the path.

Once that was done, Save to clipboard works fine on a Medium page, but save to file does nothing. No error message and no file in ~/Desktop.

Any thoughts on what I'm doing wrong?

Thanks,

Ollie

**Comment by ttscoff** [comment]
Are you saving to file via the shortcut, or with `--file`? If with `--file`, are you providing an absolute path (full, without ~)?

**Comment by OllieA** [comment]
I'm using the shortcut. The file option in the downloaded shortcut was
--file "~/Desktop/%date Clipped Page.md" which did nothing. I changed to absolute path still to Desktop with no result. Changed to absolute path to Downloads. Still no results.

As noted above, the Gather shortcut works fine when I select the Copy to Clipboard option. It's only the Save File option that gives me problems.

Thanks,

Ollie

**Comment by ttscoff** [comment]
Can you show me the full command you're using? And does the same command 
work if you run it in Terminal?

Thanks,
Brett

**Comment by OllieA** [comment]
Here is the command in the "Save File" branch of the shortcut:
/opt/homebrew/bin/gather --stdin --metadata --html --file "Users/oacheson/Downloads/%date Clipped Page.md"

I then ran the following in terminal
/opt/homebrew/bin/gather --metadata --file "Users/oacheson/Downloads/%date Clipped Page.md" https://brettterpstra.com

And got the following error
Failed writing to file: Users/oacheson/Downloads/2022-09-10 12:05 Clipped Page.md, Error: The folder “2022-09-10 12/05 Clipped Page.md” doesn’t exist.

Aargh. Missing "/" at front of Users....

Fixed shortcut and it now works.

Thanks for the help. This is a very handy app.

Ollie

**Comment by ttscoff** [comment]
Glad to hear it's working :)
